<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNvv4BfQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNvv4BfQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNvv4BfQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNvv4BfQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNvv4BfQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nvv4BfQ',
    'container.build_id' => 'ff4bf9a0',
    'container.build_time' => 1669726190,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNvv4BfQ');
